library:
  source-dirs: src
tests:
  polysemy-playground-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - polysemy-playground
copyright: 2020 Barry Moore
maintainer: moore0557@gmail.com
dependencies:
- text
- base >= 4.7 && < 5
- polysemy
- polysemy-plugin
- beam-core
- beam-sqlite
- sqlite-simple
- servant
- servant-server
- warp
- aeson
- transformers
default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies
- OverloadedStrings
name: polysemy-playground
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Barry Moore
github: barrymoo/polysemy-playground
license: BSD3
executables:
  polysemy-playground-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    dependencies:
    - polysemy-playground
description: Please see the README on GitHub at <https://github.com/barrymoo/polysemy-playground#readme>
